#!/usr/bin/env node
/**
 * sync-abi.js
 * Reads contracts/out/Speedrun.sol/Speedrun.json produced by `forge build`
 * and writes the ABI + bytecode into web/lib/abis/Speedrun.ts so the web app
 * can deploy the contract via the browser wallet.
 *
 * Usage:  node scripts/sync-abi.js
 *    or:  make sync-abi   (runs forge build first)
 */

const fs   = require('fs');
const path = require('path');

const ROOT      = path.resolve(__dirname, '..');
const ARTIFACT  = path.join(ROOT, 'contracts', 'out', 'Speedrun.sol', 'Speedrun.json');
const DEST      = path.join(ROOT, 'web', 'lib', 'abis', 'Speedrun.ts');

if (!fs.existsSync(ARTIFACT)) {
  console.error('❌  Artifact not found:', ARTIFACT);
  console.error('    Run: cd contracts && forge build');
  process.exit(1);
}

const artifact = JSON.parse(fs.readFileSync(ARTIFACT, 'utf8'));
const abi      = JSON.stringify(artifact.abi, null, 2);
const bytecode = artifact.bytecode?.object ?? artifact.bytecode ?? '0x';

const template = `// AUTO-GENERATED by scripts/sync-abi.js — do not edit manually.
// Source: contracts/src/Speedrun.sol
// Run \`make sync-abi\` to regenerate.

export const SPEEDRUN_ABI = ${abi} as const;

export const SPEEDRUN_BYTECODE: \`0x\${string}\` =
  '${bytecode}' as \`0x\${string}\`;
`;

fs.writeFileSync(DEST, template);
console.log('✅  Synced ABI + bytecode →', DEST);
console.log('   Bytecode length:', bytecode.length, 'chars');
